from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..types import (
    CircuitBreakerState,
    HealthStatus,
    LoggerMetrics,
    LogLevel,
    TransportHealth,
    TransportMetrics,
)
from .entities import LogEntryEntity


class BufferMetrics(Protocol):
    size: int
    max_size: int
    oldest_entry: float | None
    newest_entry: float | None
    memory_usage_mb: float
    dropped_entries: int


class ILogBuffer(Protocol):
    def add(self, entry: LogEntryEntity) -> None: ...

    def flush(self) -> list[LogEntryEntity]: ...

    def peek(self) -> list[LogEntryEntity]: ...

    def size(self) -> int: ...

    def is_full(self) -> bool: ...

    def should_flush(self) -> bool: ...

    def clear(self) -> None: ...

    def destroy(self) -> None: ...

    def get_metrics(self) -> dict[str, Any]: ...


class ILogFilter(Protocol):
    def should_process(self, entry: LogEntryEntity) -> bool: ...

    def filter(self, entry: LogEntryEntity) -> LogEntryEntity: ...

    def is_level_enabled(self, level: LogLevel) -> bool: ...


class ILogTransport(Protocol):
    def send(self, entries: list[LogEntryEntity]) -> None: ...

    def is_available(self) -> bool: ...

    def get_health(self) -> TransportHealth: ...

    def get_metrics(self) -> TransportMetrics | None: ...

    def destroy(self) -> None: ...


class IDeadLetterQueue(Protocol):
    def add(self, entry: LogEntryEntity, reason: str) -> dict[str, int]: ...

    def add_batch(self, entries: list[LogEntryEntity], reason: str) -> dict[str, int]: ...

    def flush(self) -> int: ...

    def size(self) -> int: ...

    def clear(self) -> None: ...

    def get_entries(self, limit: int = 100) -> list[dict[str, Any]]: ...

    def get_stats(self) -> dict[str, int]: ...


class ICircuitBreaker(Protocol):
    def execute(self, operation: Any) -> Any: ...

    def record_success(self) -> None: ...

    def record_failure(self, error: Exception | None = None) -> None: ...

    def get_state(self) -> dict[str, Any]: ...

    def reset(self) -> None: ...


class IContextProvider(Protocol):
    def get_context(self) -> dict[str, Any]: ...

    def run_with_context(self, context: dict[str, Any], fn: Any) -> Any: ...

    async def run_with_context_async(self, context: dict[str, Any], fn: Any) -> Any: ...

    def set(self, key: str, value: Any) -> None: ...

    def get(self, key: str, default: Any = None) -> Any: ...

    def clear(self) -> None: ...


@runtime_checkable
class ILogger(Protocol):
    def debug(self, message: str, context: dict[str, Any] | None = None) -> None: ...

    def info(self, message: str, context: dict[str, Any] | None = None) -> None: ...

    def warn(self, message: str, context: dict[str, Any] | None = None) -> None: ...

    def error(self, message: str, context: dict[str, Any] | None = None) -> None: ...

    def fatal(self, message: str, context: dict[str, Any] | None = None) -> None: ...

    def log(self, level: LogLevel, message: str, context: dict[str, Any] | None = None) -> None: ...

    def track_event(self, event_name: str, properties: dict[str, Any] | None = None) -> None: ...

    def flush(self) -> None: ...

    async def aflush(self) -> None: ...

    def with_context(self, context: dict[str, Any], fn: Any) -> Any: ...

    async def with_context_async(self, context: dict[str, Any], fn: Any) -> Any: ...

    def get_metrics(self) -> LoggerMetrics: ...

    def get_health(self) -> HealthStatus: ...

    def destroy(self) -> None: ...

    async def adestroy(self) -> None: ...


class ILogInterceptor(Protocol):
    def enable(self) -> None: ...

    def restore(self) -> None: ...

    def is_enabled(self) -> bool: ...


class CircuitBreakerSnapshot(Protocol):
    state: CircuitBreakerState
